import { useEffect, useRef, useState } from "react";
import { Scan, AlertTriangle, Bug, Brain } from "lucide-react";
import chainshieldLogo from "@/assets/chainshield-logo.png";

const features = [
  {
    icon: Scan,
    title: "Scan Any Contract Instantly",
    description: "Analyze any ERC-20, ERC-721, or custom contract in seconds.",
    color: "primary",
  },
  {
    icon: AlertTriangle,
    title: "Rugpull & Scam Detection",
    description: "Find hidden owner powers, liquidity drain methods, and malicious functions.",
    color: "destructive",
  },
  {
    icon: Bug,
    title: "Honeypot & Mint Analysis",
    description: "Detect tokens that block selling or allow infinite minting.",
    color: "accent",
  },
  {
    icon: Brain,
    title: "AI-Powered Reports",
    description: "Readable analysis generated by advanced AI and static analysis.",
    color: "primary",
  },
];

export function FeaturesGrid() {
  const sectionRef = useRef<HTMLElement>(null);
  const [isVisible, setIsVisible] = useState(false);

  useEffect(() => {
    const observer = new IntersectionObserver(
      ([entry]) => {
        if (entry.isIntersecting) {
          setIsVisible(true);
        }
      },
      { threshold: 0.1 }
    );

    if (sectionRef.current) {
      observer.observe(sectionRef.current);
    }

    return () => observer.disconnect();
  }, []);

  return (
    <section
      ref={sectionRef}
      id="features"
      className="relative py-32"
    >
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Section header */}
        <div className="text-center mb-16">
          <h2 className="font-display font-bold text-3xl sm:text-4xl lg:text-5xl mb-4">
            Powerful <span className="text-gradient">Security Features</span>
          </h2>
          <p className="text-muted-foreground text-lg max-w-2xl mx-auto">
            Everything you need to protect your investments from smart contract threats.
          </p>
        </div>

        {/* Feature cards grid */}
        <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-6 mb-16">
          {features.map((feature, index) => {
            const Icon = feature.icon;
            return (
              <div
                key={feature.title}
                className={`group relative card-gradient rounded-2xl p-6 border border-border/50 hover:border-primary/50 transition-all duration-500 hover:-translate-y-2 card-shadow ${
                  isVisible ? "opacity-100 translate-y-0" : "opacity-0 translate-y-10"
                }`}
                style={{ transitionDelay: `${index * 100}ms` }}
              >
                {/* Icon */}
                <div className={`w-14 h-14 rounded-xl flex items-center justify-center mb-4 bg-${feature.color}/10 group-hover:bg-${feature.color}/20 transition-colors`}>
                  <Icon className={`w-7 h-7 text-${feature.color}`} />
                </div>

                {/* Content */}
                <h3 className="font-display font-semibold text-lg mb-2 text-foreground">
                  {feature.title}
                </h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  {feature.description}
                </p>

                {/* Hover glow */}
                <div className="absolute inset-0 rounded-2xl bg-primary/5 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none" />
              </div>
            );
          })}
        </div>

        {/* Center illustration */}
        <div className={`flex justify-center transition-all duration-1000 delay-500 ${isVisible ? "opacity-100 scale-100" : "opacity-0 scale-90"}`}>
          <div className="relative">
            <div className="absolute inset-0 bg-primary/20 rounded-full blur-3xl animate-glow-pulse" />
            <img
              src={chainshieldLogo}
              alt="ChainShield"
              className="w-40 h-40 object-contain relative z-10 animate-float"
              style={{ filter: "drop-shadow(0 0 40px hsl(217 91% 60% / 0.3))" }}
            />
          </div>
        </div>
      </div>
    </section>
  );
}
